### ISSUE TITLE
PRACTICA 2

### ISSUE THREAD

**Issue by AmilkarVladimiR** [SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equiposcc#1]
[Practica 2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equiposcc/files/11594504/Practica.2.pdf)

**Comment by MariaJose-1007** [comment]
Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho...
